# Generated by Django 4.1.1 on 2023-04-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kr_backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
