# Generated by Django 4.1.1 on 2023-04-06 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kr_backend', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
