# Generated by Django 4.1.1 on 2023-04-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kr_backend', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='article',
        ),
    ]
