# Generated by Django 4.1.1 on 2023-05-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kr_backend', '0008_post_date_review_date'),
    ]
    sql = """CREATE OR REPLACE SQL SECURITY INVOKER VIEW post_info_view AS
                SELECT ROW_NUMBER() OVER (
                ORDER BY kr_st.kr_backend_post.title) id, kr_st.kr_backend_post.title, kr_st.kr_backend_post.user_id as id_poster, 
                CONCAT_WS(' ', kr_st.kr_backend_user.first_name, kr_st.kr_backend_user.last_name) as username_reviewer, 
                kr_st.kr_backend_review.post_id as id_post, kr_backend_review.user_id as id_reviewer FROM kr_st.kr_backend_review 
                    LEFT JOIN kr_st.kr_backend_post on (kr_st.kr_backend_review.post_id = kr_st.kr_backend_post.id)
                    LEFT JOIN kr_st.kr_backend_user on (kr_st.kr_backend_review.user_id = kr_st.kr_backend_user.id);"""

    operations = [
        migrations.RunSQL(sql),
        migrations.CreateModel(
            name='PostInfoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.IntegerField()),
                ('id_reviewer', models.IntegerField()),
                ('id_poster', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('username_reviewer', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'post_info',
                'verbose_name_plural': 'post_info',
                'db_table': 'post_info_view',
                'managed': False,
            },
        ),
    ]
