# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: email.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65mail.proto\x12\temailinfo\"\x1f\n\rEmailResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"G\n\x0c\x45mailRequest\x12\x19\n\x11username_reviewer\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2M\n\x0c\x45mailService\x12=\n\x08GetEmail\x12\x17.emailinfo.EmailRequest\x1a\x18.emailinfo.EmailResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'email_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMAILRESPONSE._serialized_start=26
  _EMAILRESPONSE._serialized_end=57
  _EMAILREQUEST._serialized_start=59
  _EMAILREQUEST._serialized_end=130
  _EMAILSERVICE._serialized_start=132
  _EMAILSERVICE._serialized_end=209
# @@protoc_insertion_point(module_scope)
